[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF" # Light Background
secondaryBackgroundColor = "#F0F2F6" # Light secondary background
textColor = "#31333F" # Dark blue text
font = "sans serif"
[ui]
hideTopBar = true

[client]
toolbarMode = "minimal"